import "server-only";
import Database from "better-sqlite3";
import postgres from "postgres";
import path from "node:path";
import type { SharedResult,SubmitResult } from "@/lib/types";

const isPostgres=()=>process.env.UNTRACED_DATABASE==="postgres"&&!!process.env.DATABASE_URL;
let pg:ReturnType<typeof postgres>|undefined;const sql=()=>pg??=postgres(process.env.DATABASE_URL!,{max:4,prepare:false});
const createLocal=(db:Database.Database)=>db.exec("CREATE TABLE IF NOT EXISTS share_results(share_id TEXT PRIMARY KEY,route_key TEXT NOT NULL,created_at TEXT NOT NULL,was_first_discovery INTEGER NOT NULL,discovery_ordinal INTEGER NOT NULL,route_submission_count INTEGER NOT NULL,personal_streak INTEGER NOT NULL,personally_submitted_before INTEGER NOT NULL)");

export async function saveShare(shareId:string,key:string,result:SubmitResult){if(isPostgres()){await sql()`INSERT INTO share_results(share_id,route_key,was_first_discovery,discovery_ordinal,route_submission_count,personal_streak,personally_submitted_before) SELECT ${shareId}::uuid,${key},${result.isNewDiscovery},discovery_ordinal,${result.submissionCount},${result.personal.currentStreak},${result.personallySubmittedBefore} FROM patterns WHERE route_key=${key}`;return}const db=new Database(path.join(process.cwd(),".data","untraced.sqlite"));createLocal(db);const pattern=db.prepare("SELECT discovery_ordinal FROM patterns WHERE route_key=?").get(key) as {discovery_ordinal:number};db.prepare("INSERT INTO share_results VALUES(?,?,?,?,?,?,?,?)").run(shareId,key,new Date().toISOString(),result.isNewDiscovery?1:0,pattern.discovery_ordinal,result.submissionCount,result.personal.currentStreak,result.personallySubmittedBefore?1:0);db.close()}

export async function getSharedResult(shareId:string):Promise<SharedResult|null>{if(!/^[0-9a-f-]{36}$/i.test(shareId))return null;if(isPostgres()){const rows=await sql()`SELECT s.*,p.first_discoverer_name FROM share_results s JOIN patterns p USING(route_key) WHERE s.share_id=${shareId}::uuid`;return rows[0]?shape(rows[0]):null}const db=new Database(path.join(process.cwd(),".data","untraced.sqlite"),{readonly:false});createLocal(db);const row=db.prepare("SELECT s.*,p.first_discoverer_name FROM share_results s JOIN patterns p USING(route_key) WHERE s.share_id=?").get(shareId) as Record<string,unknown>|undefined;db.close();return row?shape(row):null}
function shape(row:Record<string,unknown>):SharedResult{return{shareId:String(row.share_id),route:String(row.route_key).split("").map(Number),wasFirstDiscovery:Boolean(row.was_first_discovery),discoveryOrdinal:Number(row.discovery_ordinal),routeSubmissionCount:Number(row.route_submission_count),personalStreak:Number(row.personal_streak),personallySubmittedBefore:Boolean(row.personally_submitted_before),submittedAt:new Date(String(row.created_at)).toISOString(),firstDiscovererName:row.first_discoverer_name?String(row.first_discoverer_name):null}}
