/* eslint-disable react-hooks/rules-of-hooks, @typescript-eslint/no-explicit-any */
import "server-only";
import Database from "better-sqlite3";
import postgres from "postgres";
import { mkdirSync } from "node:fs";
import path from "node:path";
import { isValidRoute, routeKey, type NodeId } from "@/lib/patterns";
import { MILESTONES, TOTAL_PATTERNS } from "@/lib/constants";
import type { PersonalHistoryEntry, Progress, PublicPattern, SubmitResult } from "@/lib/types";
import { saveShare } from "@/server/shares";

const TOTAL=TOTAL_PATTERNS, thresholds=MILESTONES.map(({threshold,count})=>[threshold,count] as const);
const cleanName=(v:unknown)=>typeof v==="string"&&/^[\p{L}\p{N} _.'-]{1,24}$/u.test(v.trim())?v.trim():null;
let local:Database.Database|undefined;
function sqlite(){if(local)return local;mkdirSync(path.join(process.cwd(),".data"),{recursive:true});local=new Database(path.join(process.cwd(),".data","untraced.sqlite"));local.pragma("journal_mode = WAL");local.exec(`CREATE TABLE IF NOT EXISTS hunt_state(id INTEGER PRIMARY KEY CHECK(id=1),hunt_started_at TEXT NOT NULL,completed_at TEXT,final_route_key TEXT,final_discoverer_name TEXT,next_ordinal INTEGER NOT NULL);CREATE TABLE IF NOT EXISTS patterns(route_key TEXT PRIMARY KEY,first_discovered_at TEXT NOT NULL,first_discoverer_id TEXT,first_discoverer_name TEXT,discovery_ordinal INTEGER NOT NULL UNIQUE,submission_count INTEGER NOT NULL,last_submitted_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS submissions(id TEXT PRIMARY KEY,route_key TEXT NOT NULL,submitted_at TEXT NOT NULL,player_id TEXT NOT NULL,was_first_discovery INTEGER NOT NULL);CREATE INDEX IF NOT EXISTS submissions_time_idx ON submissions(submitted_at);CREATE INDEX IF NOT EXISTS submissions_player_idx ON submissions(player_id);CREATE TABLE IF NOT EXISTS milestones(threshold TEXT PRIMARY KEY,discovered_count INTEGER NOT NULL,reached_at TEXT NOT NULL);INSERT OR IGNORE INTO hunt_state VALUES(1,datetime('now'),NULL,NULL,NULL,1);`);return local}
const usePg=()=>process.env.UNTRACED_DATABASE==="postgres"&&!!process.env.DATABASE_URL;
let pg:ReturnType<typeof postgres>|undefined;const sql=()=>pg??=postgres(process.env.DATABASE_URL!,{max:10,prepare:false});
async function existingOrdinal(key:string){if(usePg())return Number((await sql()`SELECT discovery_ordinal FROM patterns WHERE route_key=${key}`)[0].discovery_ordinal);return Number((sqlite().prepare("SELECT discovery_ordinal FROM patterns WHERE route_key=?").get(key) as {discovery_ordinal:number}).discovery_ordinal)}
export async function submit(input:{route:unknown;playerId:string;nickname?:unknown}):Promise<SubmitResult>{if(!isValidRoute(input.route))throw new Error("INVALID_ROUTE");if(!/^[0-9a-f-]{36}$/i.test(input.playerId))throw new Error("INVALID_PLAYER");const name=cleanName(input.nickname),key=routeKey(input.route as NodeId[]),result=usePg()?await submitPg(key,input.playerId,name):submitLocal(key,input.playerId,name);if(result.ordinal===null)result.ordinal=await existingOrdinal(key);const shareId=crypto.randomUUID();await saveShare(shareId,key,result);return{shareId,...result}}
function submitLocal(key:string,playerId:string,name:string|null):SubmitResult{const db=sqlite(),now=new Date().toISOString();return db.transaction(()=>{const prior=db.prepare("SELECT * FROM patterns WHERE route_key=?").get(key) as Record<string,unknown>|undefined;const personally=(db.prepare("SELECT 1 FROM submissions WHERE route_key=? AND player_id=? LIMIT 1").get(key,playerId))!==undefined;let isNew=false,ordinal:number|null=null,firstAt=now,firstName=name,count=1;if(prior){count=Number(prior.submission_count)+1;firstAt=String(prior.first_discovered_at);firstName=prior.first_discoverer_name as string|null;db.prepare("UPDATE patterns SET submission_count=?,last_submitted_at=? WHERE route_key=?").run(count,now,key)}else{const state=db.prepare("SELECT next_ordinal FROM hunt_state WHERE id=1").get() as {next_ordinal:number};ordinal=state.next_ordinal;isNew=true;db.prepare("UPDATE hunt_state SET next_ordinal=next_ordinal+1 WHERE id=1").run();db.prepare("INSERT INTO patterns VALUES(?,?,?,?,?,?,?)").run(key,now,playerId,name,ordinal,1,now)}db.prepare("INSERT INTO submissions VALUES(?,?,?,?,?)").run(crypto.randomUUID(),key,now,playerId,isNew?1:0);const discovered=(db.prepare("SELECT COUNT(*) n FROM patterns").get() as {n:number}).n;for(const[t,n]of thresholds)if(discovered>=n)db.prepare("INSERT OR IGNORE INTO milestones VALUES(?,?,?)").run(t,discovered,now);let completedAt=(db.prepare("SELECT completed_at FROM hunt_state WHERE id=1").get() as {completed_at:string|null}).completed_at;if(discovered===TOTAL&&!completedAt){completedAt=now;db.prepare("UPDATE hunt_state SET completed_at=?,final_route_key=?,final_discoverer_name=? WHERE id=1 AND completed_at IS NULL").run(now,key,name)}const p=db.prepare("SELECT COUNT(*) attempts,COUNT(DISTINCT route_key) distinct_routes,SUM(was_first_discovery) discoveries FROM submissions WHERE player_id=?").get(playerId) as {attempts:number;distinct_routes:number;discoveries:number};const streak=streaks(db.prepare("SELECT was_first_discovery FROM submissions WHERE player_id=? ORDER BY submitted_at").all(playerId) as {was_first_discovery:number}[]);return{isNewDiscovery:isNew,ordinal,submissionCount:count,firstDiscoveredAt:firstAt,firstDiscovererName:firstName,discoveredTotal:discovered,totalSubmissions:(db.prepare("SELECT COUNT(*) n FROM submissions").get() as {n:number}).n,personallySubmittedBefore:personally,personal:{attempts:p.attempts,discoveries:p.discoveries||0,distinct:p.distinct_routes,selfRepeats:p.attempts-p.distinct_routes,currentStreak:streak.current,bestStreak:streak.best},completedAt}})()}
async function submitPg(key:string,playerId:string,name:string|null):Promise<SubmitResult>{const rows=await sql().begin(async tx=>{const locked=await tx`SELECT * FROM hunt_state WHERE id=1 FOR UPDATE`;if(!locked.length)await tx`INSERT INTO hunt_state(id) VALUES(1)`;const previous=await tx`SELECT * FROM patterns WHERE route_key=${key}`;const personally=(await tx`SELECT 1 FROM submissions WHERE route_key=${key} AND player_id=${playerId}::uuid LIMIT 1`).length>0;let isNew=false,ordinal:null|number=null,pattern;if(previous.length){pattern=(await tx`UPDATE patterns SET submission_count=submission_count+1,last_submitted_at=now() WHERE route_key=${key} RETURNING *`)[0]}else{const state=(await tx`SELECT next_ordinal FROM hunt_state WHERE id=1 FOR UPDATE`)[0];ordinal=state.next_ordinal;await tx`UPDATE hunt_state SET next_ordinal=next_ordinal+1 WHERE id=1`;pattern=(await tx`INSERT INTO patterns(route_key,first_discoverer_id,first_discoverer_name,discovery_ordinal) VALUES(${key},${playerId}::uuid,${name},${ordinal}) RETURNING *`)[0];isNew=true}await tx`INSERT INTO submissions(route_key,player_id,was_first_discovery) VALUES(${key},${playerId}::uuid,${isNew})`;const discovered=Number((await tx`SELECT COUNT(*) n FROM patterns`)[0].n);for(const[t,n]of thresholds)if(discovered>=n)await tx`INSERT INTO milestones(threshold,discovered_count) VALUES(${t},${discovered}) ON CONFLICT DO NOTHING`;if(discovered===TOTAL)await tx`UPDATE hunt_state SET completed_at=COALESCE(completed_at,now()),final_route_key=COALESCE(final_route_key,${key}),final_discoverer_name=COALESCE(final_discoverer_name,${name}) WHERE id=1`;const stats=(await tx`SELECT COUNT(*) attempts,COUNT(DISTINCT route_key) distinct_routes,COUNT(*) FILTER(WHERE was_first_discovery) discoveries FROM submissions WHERE player_id=${playerId}::uuid`)[0];const history=await tx`SELECT was_first_discovery FROM submissions WHERE player_id=${playerId}::uuid ORDER BY submitted_at`;return{isNew,ordinal,pattern,personally,discovered,stats,history,total:Number((await tx`SELECT COUNT(*) n FROM submissions`)[0].n),completed:(await tx`SELECT completed_at FROM hunt_state WHERE id=1`)[0].completed_at}});const r=rows,s=streaks(r.history.map(x=>({was_first_discovery:x.was_first_discovery?1:0})));return{isNewDiscovery:r.isNew,ordinal:r.ordinal,submissionCount:Number(r.pattern.submission_count),firstDiscoveredAt:new Date(r.pattern.first_discovered_at).toISOString(),firstDiscovererName:r.pattern.first_discoverer_name,discoveredTotal:r.discovered,totalSubmissions:r.total,personallySubmittedBefore:r.personally,personal:{attempts:Number(r.stats.attempts),discoveries:Number(r.stats.discoveries),distinct:Number(r.stats.distinct_routes),selfRepeats:Number(r.stats.attempts)-Number(r.stats.distinct_routes),currentStreak:s.current,bestStreak:s.best},completedAt:r.completed?new Date(r.completed).toISOString():null}}
function streaks(rows:{was_first_discovery:number}[]){let current=0,best=0;for(const r of rows){current=r.was_first_discovery?current+1:0;best=Math.max(best,current)}return{current,best}}
export async function getPublicPatternByOrdinal(ordinal:number):Promise<PublicPattern|null>{if(!Number.isInteger(ordinal)||ordinal<1||ordinal>TOTAL)return null;let row:any;if(usePg())row=(await sql()`SELECT route_key,submission_count,discovery_ordinal,first_discovered_at,first_discoverer_name FROM patterns WHERE discovery_ordinal=${ordinal}`)[0];else row=sqlite().prepare("SELECT route_key,submission_count,discovery_ordinal,first_discovered_at,first_discoverer_name FROM patterns WHERE discovery_ordinal=?").get(ordinal);if(!row)return null;return{route:String(row.route_key).split("").map(Number),count:Number(row.submission_count),ordinal:Number(row.discovery_ordinal),firstDiscoveredAt:new Date(row.first_discovered_at).toISOString(),name:row.first_discoverer_name??null}}
export async function personalHistory(playerId:string):Promise<PersonalHistoryEntry[]>{if(!/^[0-9a-f-]{36}$/i.test(playerId))throw new Error("INVALID_PLAYER");const map=(r:any)=>({route:String(r.route_key).split("").map(Number),new:Boolean(r.was_first_discovery),ordinal:Number(r.discovery_ordinal),at:new Date(r.submitted_at).toISOString(),count:Number(r.submission_count)});if(usePg()){const rows=await sql()`SELECT s.route_key,s.submitted_at,s.was_first_discovery,p.discovery_ordinal,p.submission_count FROM submissions s JOIN patterns p USING(route_key) WHERE s.player_id=${playerId}::uuid ORDER BY s.submitted_at DESC,s.id DESC`;return rows.map(map)}const db=sqlite(),rows=db.prepare("SELECT s.route_key,s.submitted_at,s.was_first_discovery,p.discovery_ordinal,p.submission_count FROM submissions s JOIN patterns p ON p.route_key=s.route_key WHERE s.player_id=? ORDER BY s.submitted_at DESC,s.id DESC").all(playerId);return rows.map(map)}
export async function progress():Promise<Progress>{if(usePg()){const db=sql();const [counts,state,recent,popular,marks]=await Promise.all([db`SELECT (SELECT COUNT(*) FROM patterns) discovered,(SELECT COUNT(*) FROM submissions) submissions,(SELECT COUNT(DISTINCT player_id) FROM submissions) browsers`,db`SELECT * FROM hunt_state WHERE id=1`,db`SELECT p.route_key,p.submission_count,p.discovery_ordinal,p.first_discovered_at,p.first_discoverer_name,s.submitted_at entry_at,s.was_first_discovery FROM submissions s JOIN patterns p USING(route_key) ORDER BY s.submitted_at DESC LIMIT 8`,db`SELECT route_key,submission_count,discovery_ordinal,first_discovered_at,first_discoverer_name FROM patterns WHERE submission_count>1 ORDER BY submission_count DESC,first_discovered_at DESC LIMIT 8`,db`SELECT threshold,discovered_count,reached_at FROM milestones ORDER BY reached_at`]);return shapeProgress(counts[0],state[0],recent,popular,marks)}const db=sqlite(),counts=db.prepare("SELECT (SELECT COUNT(*) FROM patterns) discovered,(SELECT COUNT(*) FROM submissions) submissions,(SELECT COUNT(DISTINCT player_id) FROM submissions) browsers").get(),state=db.prepare("SELECT * FROM hunt_state WHERE id=1").get(),recent=db.prepare("SELECT p.route_key,p.submission_count,p.discovery_ordinal,p.first_discovered_at,p.first_discoverer_name,s.submitted_at entry_at,s.was_first_discovery FROM submissions s JOIN patterns p ON p.route_key=s.route_key ORDER BY s.submitted_at DESC LIMIT 8").all(),popular=db.prepare("SELECT route_key,submission_count,discovery_ordinal,first_discovered_at,first_discoverer_name FROM patterns WHERE submission_count>1 ORDER BY submission_count DESC,first_discovered_at DESC LIMIT 8").all(),marks=db.prepare("SELECT threshold,discovered_count,reached_at FROM milestones ORDER BY reached_at").all();return shapeProgress(counts,state,recent,popular,marks)}
function shapeProgress(c:any,s:any,recent:any[],popular:any[],marks:any[]):Progress{const map=(r:any)=>({route:String(r.route_key).split("").map(Number),count:Number(r.submission_count),ordinal:Number(r.discovery_ordinal),firstDiscoveredAt:new Date(r.first_discovered_at).toISOString(),name:r.first_discoverer_name??null,entryAt:r.entry_at?new Date(r.entry_at).toISOString():undefined,wasFirstDiscovery:r.was_first_discovery===undefined?undefined:Boolean(r.was_first_discovery)});return{discovered:Number(c.discovered),totalSubmissions:Number(c.submissions),browsers:Number(c.browsers),huntStartedAt:new Date(s.hunt_started_at).toISOString(),completedAt:s.completed_at?new Date(s.completed_at).toISOString():null,recent:recent.map(map),popular:popular.map(map),milestones:marks.map(m=>({threshold:m.threshold,discoveredCount:Number(m.discovered_count),reachedAt:new Date(m.reached_at).toISOString()}))}}
