"use client";
import { useCallback,useEffect,useRef,useState } from "react";
import Header from "./Header";
import ShareButton from "./ShareButton";
import { TOTAL_PATTERNS } from "@/lib/constants";
import { crossedNodes,formatPercent,formatRelativeTime,requiredMidpoint,type NodeId } from "@/lib/patterns";
import type { Progress,SubmitResult } from "@/lib/types";
import styles from "@/app/page.module.css";
import componentStyles from "./PatternGame.module.css";
const nodes=[1,2,3,4,5,6,7,8,9] as NodeId[];const pos=(n:number)=>({x:((n-1)%3)*100+50,y:Math.floor((n-1)/3)*100+50});
function identity(){let id=localStorage.getItem("untraced-player-id");if(!id){id=crypto.randomUUID();localStorage.setItem("untraced-player-id",id)}return id}
export default function PatternGame({initialProgress}:Readonly<{initialProgress:Progress}>){
 const [progress,setProgress]=useState(initialProgress),[route,setRoute]=useState<NodeId[]>([]),[pointer,setPointer]=useState<{x:number;y:number}|null>(null),[drawing,setDrawing]=useState(false),[status,setStatus]=useState("Start on any dot."),[result,setResult]=useState<SubmitResult|null>(null),[sending,setSending]=useState(false),[failed,setFailed]=useState(false),[muted,setMuted]=useState(true);const surface=useRef<HTMLDivElement>(null),last=useRef<{x:number;y:number}|null>(null),routeRef=useRef<NodeId[]>([]),audio=useRef<AudioContext|null>(null);
 useEffect(()=>{queueMicrotask(()=>setMuted(localStorage.getItem("untraced-muted")!=="false"));const timer=setInterval(async()=>{try{const r=await fetch("/api/progress");if(r.ok)setProgress(await r.json())}catch{}},15000);return()=>clearInterval(timer)},[]);
 const tick=useCallback((complete=false)=>{if(muted||matchMedia("(prefers-reduced-motion: reduce)").matches)return;audio.current??=new AudioContext();const ctx=audio.current,o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=complete?510:310+routeRef.current.length*18;g.gain.setValueAtTime(.035,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+.055);o.connect(g).connect(ctx.destination);o.start();o.stop(ctx.currentTime+.06)},[muted]);
 const acquire=useCallback((ids:NodeId[])=>{const next=[...routeRef.current];for(const id of ids){if(next.includes(id))continue;if(next.length){const mid=requiredMidpoint(next.at(-1)!,id);if(mid&&!next.includes(mid)){next.push(mid);tick(next.length===9)}}next.push(id);tick(next.length===9)}routeRef.current=next;setRoute(next);setStatus(`${next.length} of 9.`)},[tick]);
 const coords=(e:React.PointerEvent)=>{const r=surface.current!.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*300,y:(e.clientY-r.top)/r.height*300}};
 const submitRoute=useCallback(async()=>{if(routeRef.current.length!==9){setStatus("All nine dots are required.");setTimeout(()=>{routeRef.current=[];setRoute([]);setPointer(null)},420);return}setSending(true);setFailed(false);try{const r=await fetch("/api/submit",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({route:routeRef.current,playerId:identity(),nickname:localStorage.getItem("untraced-nickname")||undefined,website:""})});const body=await r.json();if(!r.ok)throw new Error(body.error);setResult(body);setProgress(p=>({...p,discovered:body.discoveredTotal,totalSubmissions:body.totalSubmissions,completedAt:body.completedAt}));setStatus(body.isNewDiscovery?"First find.":"Pattern already found.");const history=JSON.parse(localStorage.getItem("untraced-history")||"[]");history.unshift({route:routeRef.current,new:body.isNewDiscovery,ordinal:body.ordinal,at:new Date().toISOString(),count:body.submissionCount});localStorage.setItem("untraced-history",JSON.stringify(history.slice(0,150)))}catch(e){setFailed(true);setStatus(e instanceof Error?e.message:"Could not save the pattern.")}finally{setSending(false)}},[]);
 const start=(e:React.PointerEvent,id:NodeId)=>{if(sending)return;if(result){setResult(null);routeRef.current=[];setRoute([])}e.currentTarget.setPointerCapture(e.pointerId);setDrawing(true);const p=coords(e);last.current=p;setPointer(p);acquire([id])};
 const move=(e:React.PointerEvent)=>{if(!drawing)return;const p=coords(e),centers=nodes.map(id=>({...pos(id),id}));acquire(crossedNodes(last.current??p,p,centers,22));last.current=p;setPointer(p)};
 const end=(e:React.PointerEvent)=>{if(!drawing)return;const p=coords(e),centers=nodes.map(id=>({...pos(id),id}));acquire(crossedNodes(last.current??p,p,centers,22));last.current=p;setDrawing(false);setPointer(null);if(routeRef.current.length===9)void submitRoute();else setStatus(`${routeRef.current.length} of 9. Continue or clear.`)};
 const cancel=()=>{if(!drawing)return;setDrawing(false);setPointer(null);setStatus(`${routeRef.current.length} of 9. Continue or clear.`)};
 const keyboard=(id:NodeId)=>{if(result){setResult(null);routeRef.current=[];setRoute([])}acquire([id]);if(routeRef.current.length===9)setStatus("Complete route. Press Submit route.")};
 const reset=()=>{routeRef.current=[];setRoute([]);setPointer(null);setResult(null);setFailed(false);setStatus("Start on any dot.")};const points=route.map(n=>pos(n));
 return <main className={`${styles.shell} ${componentStyles.viewportShell}`}><Header/><section className={styles.game} aria-labelledby="game-title">
  <div className={styles.progressBlock}><p className={styles.eyebrow}>{progress.completedAt?"Complete":"Found worldwide"}</p><p className={styles.count}><strong>{progress.discovered.toLocaleString()}</strong><span> / {TOTAL_PATTERNS.toLocaleString()}</span></p><p className={styles.percent}>{formatPercent(progress.discovered)}</p><div className={styles.traceProgress} style={{"--progress":progress.discovered?`max(2px, ${progress.discovered/TOTAL_PATTERNS*100}%)`:"0%"} as React.CSSProperties} role="progressbar" aria-valuemin={0} aria-valuemax={TOTAL_PATTERNS} aria-valuenow={progress.discovered}/></div>
   <div className={styles.instrument}><div className={styles.prompt}>{result?<><p className={`${styles.resultLabel} ${result.isNewDiscovery?styles.newResult:""}`}>{result.isNewDiscovery?"UNTRACED.":"ALREADY FOUND."}</p><h1 id="game-title">{result.isNewDiscovery?`Pattern #${result.ordinal?.toLocaleString()}`:`Seen ${result.submissionCount.toLocaleString()} ${result.submissionCount===1?"time":"times"}`}</h1><p>{result.isNewDiscovery?`${(TOTAL_PATTERNS-result.discoveredTotal).toLocaleString()} patterns remain.`:result.personallySubmittedBefore?"You’ve entered this one before.":`First entered ${formatRelativeTime(result.firstDiscoveredAt)}.`}</p></>:<><h1 id="game-title">Draw a line through all nine.</h1><p>Complete all nine to check it.</p></>}</div>
   <div ref={surface} className={`${styles.grid} ${componentStyles.cleanGrid} ${result?.isNewDiscovery?componentStyles.discoveryPulse:result?componentStyles.duplicateResult:""} ${sending?styles.sending:""}`} role="application" aria-label="Nine-dot pattern grid" onPointerMove={move} onPointerUp={end} onPointerCancel={cancel} onContextMenu={e=>e.preventDefault()}><svg viewBox="0 0 300 300" aria-hidden="true"><polyline points={points.map(p=>`${p.x},${p.y}`).join(" ")}/>{drawing&&pointer&&points.length>0&&<line x1={points.at(-1)!.x} y1={points.at(-1)!.y} x2={pointer.x} y2={pointer.y}/>}</svg>{nodes.map(id=><button key={id} type="button" className={route.includes(id)?styles.dotActive:styles.dot} aria-label={`Dot ${id}${route.includes(id)?`, position ${route.indexOf(id)+1}`:""}`} onPointerDown={e=>start(e,id)} onClick={e=>{if(!drawing&&e.detail===0)keyboard(id)}}><span>{route.indexOf(id)+1||""}</span></button>)}</div>
   <div className={styles.actions}>{result?<><button className={styles.primary} onClick={reset}>Go again</button><ShareButton shareId={result.shareId!} route={route} isNew={result.isNewDiscovery} ordinal={result.ordinal} submissionCount={result.submissionCount} streak={result.personal.currentStreak} isRepeat={result.personallySubmittedBefore}/></>:failed?<><button className={styles.primary} disabled={sending} onClick={()=>void submitRoute()}>Retry</button><button onClick={reset}>Clear</button></>:route.length===9&&!drawing?<button className={styles.primary} disabled={sending} onClick={()=>void submitRoute()}>{sending?"Checking…":"Submit"}</button>:route.length>0&&!drawing?<button onClick={reset}>Clear</button>:null}<button aria-pressed={muted} onClick={()=>{const next=!muted;setMuted(next);localStorage.setItem("untraced-muted",String(next))}}>{muted?"Sound off":"Sound on"}</button></div>
   <p className="srOnly" aria-live="polite">{status}</p>
  </div>
  {!result&&<aside className={styles.note}><span>Still missing</span><strong>{progress.discovered===0?"All 140,704":progress.discovered===TOTAL_PATTERNS?"Nothing":(TOTAL_PATTERNS-progress.discovered).toLocaleString()}</strong><p>Visit every dot once. Crossing an unused middle dot selects it. Reversed patterns count separately.</p></aside>}
 </section></main>}
