"use client";
import { useCallback,useEffect,useRef,useState } from "react";
import Header from "./Header";
import { crossedNodes,formatPercent,requiredMidpoint,type NodeId } from "@/lib/patterns";
import type { Progress,SubmitResult } from "@/lib/types";
import styles from "@/app/page.module.css";
const nodes=[1,2,3,4,5,6,7,8,9] as NodeId[];const pos=(n:number)=>({x:((n-1)%3)*100+50,y:Math.floor((n-1)/3)*100+50});
function identity(){let id=localStorage.getItem("untraced-player-id");if(!id){id=crypto.randomUUID();localStorage.setItem("untraced-player-id",id)}return id}
export default function PatternGame({initialProgress}:Readonly<{initialProgress:Progress}>){
 const [progress,setProgress]=useState(initialProgress),[route,setRoute]=useState<NodeId[]>([]),[pointer,setPointer]=useState<{x:number;y:number}|null>(null),[drawing,setDrawing]=useState(false),[status,setStatus]=useState("Press a dot and draw continuously."),[result,setResult]=useState<SubmitResult|null>(null),[sending,setSending]=useState(false),[failed,setFailed]=useState(false),[muted,setMuted]=useState(true);const surface=useRef<HTMLDivElement>(null),last=useRef<{x:number;y:number}|null>(null),routeRef=useRef<NodeId[]>([]),audio=useRef<AudioContext|null>(null);
 useEffect(()=>{queueMicrotask(()=>setMuted(localStorage.getItem("untraced-muted")!=="false"));const timer=setInterval(async()=>{try{const r=await fetch("/api/progress");if(r.ok)setProgress(await r.json())}catch{}},15000);return()=>clearInterval(timer)},[]);
 const tick=useCallback((complete=false)=>{if(muted||matchMedia("(prefers-reduced-motion: reduce)").matches)return;audio.current??=new AudioContext();const ctx=audio.current,o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=complete?510:310+routeRef.current.length*18;g.gain.setValueAtTime(.035,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+.055);o.connect(g).connect(ctx.destination);o.start();o.stop(ctx.currentTime+.06)},[muted]);
 const acquire=useCallback((ids:NodeId[])=>{const next=[...routeRef.current];for(const id of ids){if(next.includes(id))continue;if(next.length){const mid=requiredMidpoint(next.at(-1)!,id);if(mid&&!next.includes(mid)){next.push(mid);tick(next.length===9)}}next.push(id);tick(next.length===9)}routeRef.current=next;setRoute(next);setStatus(`${next.length} of 9 dots acquired.`)},[tick]);
 const coords=(e:React.PointerEvent)=>{const r=surface.current!.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*300,y:(e.clientY-r.top)/r.height*300}};
 const submitRoute=useCallback(async()=>{if(routeRef.current.length!==9){setStatus("Use all nine dots.");setTimeout(()=>{routeRef.current=[];setRoute([]);setPointer(null)},420);return}setSending(true);setFailed(false);try{const r=await fetch("/api/submit",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({route:routeRef.current,playerId:identity(),nickname:localStorage.getItem("untraced-nickname")||undefined,website:""})});const body=await r.json();if(!r.ok)throw new Error(body.error);setResult(body);setProgress(p=>({...p,discovered:body.discoveredTotal,totalSubmissions:body.totalSubmissions,completedAt:body.completedAt}));setStatus(body.isNewDiscovery?"New global discovery.":"Route already traced.");const history=JSON.parse(localStorage.getItem("untraced-history")||"[]");history.unshift({route:routeRef.current,new:body.isNewDiscovery,at:new Date().toISOString(),count:body.submissionCount});localStorage.setItem("untraced-history",JSON.stringify(history.slice(0,150)))}catch(e){setFailed(true);setStatus(e instanceof Error?e.message:"The trace could not be recorded.")}finally{setSending(false)}},[]);
 const start=(e:React.PointerEvent,id:NodeId)=>{if(sending)return;if(result){setResult(null);routeRef.current=[];setRoute([])}e.currentTarget.setPointerCapture(e.pointerId);setDrawing(true);const p=coords(e);last.current=p;setPointer(p);acquire([id])};
 const move=(e:React.PointerEvent)=>{if(!drawing)return;const p=coords(e),centers=nodes.map(id=>({...pos(id),id}));acquire(crossedNodes(last.current??p,p,centers,22));last.current=p;setPointer(p)};
 const end=()=>{if(!drawing)return;setDrawing(false);setPointer(null);void submitRoute()};
 const keyboard=(id:NodeId)=>{if(result){setResult(null);routeRef.current=[];setRoute([])}acquire([id]);if(routeRef.current.length===9)setStatus("Complete route. Press Submit route.")};
 const reset=()=>{routeRef.current=[];setRoute([]);setPointer(null);setResult(null);setFailed(false);setStatus("Press a dot and draw continuously.")};const points=route.map(n=>pos(n));
 return <main className={styles.shell}><Header/><section className={styles.game} aria-labelledby="game-title">
  <div className={styles.progressBlock}><p className={styles.eyebrow}>{progress.completedAt?"The hunt is complete":"The communal record"}</p><p className={styles.count}><strong>{progress.discovered.toLocaleString()}</strong><span> / 140,704</span></p><p className={styles.percent}>{formatPercent(progress.discovered)} discovered</p><div className={styles.traceProgress} style={{"--progress":`${progress.discovered/140704*100}%`} as React.CSSProperties} role="progressbar" aria-valuemin={0} aria-valuemax={140704} aria-valuenow={progress.discovered}/></div>
  <div className={styles.instrument}><div className={styles.prompt}>{result?<><p className={styles.resultLabel}>{result.isNewDiscovery?"UNTRACED":"TRACED"}</p><h1 id="game-title">{result.isNewDiscovery?`Discovery ${result.ordinal?.toLocaleString()} of 140,704`:`Drawn ${result.submissionCount.toLocaleString()} ${result.submissionCount===1?"time":"times"}`}</h1><p>{result.isNewDiscovery?"You were the first to draw this route.":result.personallySubmittedBefore?"You have drawn this one before.":`First found ${new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(result.firstDiscoveredAt))}.`}</p></>:<><h1 id="game-title">Leave one careful mark.</h1><p>Use every dot. Find a route no one has.</p></>}</div>
   <div ref={surface} className={`${styles.grid} ${sending?styles.sending:""}`} role="application" aria-label="Nine-dot pattern grid" onPointerMove={move} onPointerUp={end} onPointerCancel={end} onContextMenu={e=>e.preventDefault()}><svg viewBox="0 0 300 300" aria-hidden="true"><polyline points={points.map(p=>`${p.x},${p.y}`).join(" ")}/>{drawing&&pointer&&points.length>0&&<line x1={points.at(-1)!.x} y1={points.at(-1)!.y} x2={pointer.x} y2={pointer.y}/>}</svg>{nodes.map(id=><button key={id} type="button" className={route.includes(id)?styles.dotActive:styles.dot} aria-label={`Dot ${id}${route.includes(id)?`, position ${route.indexOf(id)+1}`:""}`} onPointerDown={e=>start(e,id)} onClick={e=>{if(!drawing&&e.detail===0)keyboard(id)}}><span>{route.indexOf(id)+1||""}</span></button>)}</div>
   <div className={styles.actions}>{result?<button className={styles.primary} onClick={reset}>Trace another</button>:failed?<><button className={styles.primary} disabled={sending} onClick={()=>void submitRoute()}>Retry recording</button><button onClick={reset}>Erase</button></>:route.length===9&&!drawing?<button className={styles.primary} disabled={sending} onClick={()=>void submitRoute()}>{sending?"Recording…":"Submit route"}</button>:route.length>0&&!drawing?<button onClick={reset}>Erase trace</button>:null}<button aria-pressed={muted} onClick={()=>{const next=!muted;setMuted(next);localStorage.setItem("untraced-muted",String(next))}}>{muted?"Sound off":"Sound on"}</button></div>
   <p className={styles.warning}>Don’t draw a pattern you use on a real device.</p><p className="srOnly" aria-live="polite">{status}</p>
  </div>
  <aside className={styles.note}><span>Field note</span><strong>{progress.discovered===0?"The page is still blank.":progress.discovered===140704?"Every route was found.":`${(140704-progress.discovered).toLocaleString()} routes remain.`}</strong><p>Direction, rotation, and reflection each count separately. The midpoint rule is applied automatically as you cross a dot.</p></aside>
 </section></main>}
